import { Link, useRouterState } from "@tanstack/react-router";
import { useTranslation } from "react-i18next";
import { Bell, Bot, ChevronDown, CircleDollarSign, GraduationCap, HandCoins, HeartPulse, Home, LayoutGrid, Menu, ShieldCheck, UserRound, WalletCards } from "lucide-react";
import { Brand } from "@/components/banking/brand";
import { LanguageSwitcher } from "@/components/banking/shared";
import { Button } from "@/components/ui/button";
import { DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuLabel,DropdownMenuSeparator,DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Sheet,SheetContent,SheetHeader,SheetTitle,SheetTrigger } from "@/components/ui/sheet";
import { demoCustomers } from "@/data/bankbuddy";
import { useBankBuddy,useCustomer } from "@/stores/bankbuddy";
import { cn } from "@/lib/utils";
const items=[{to:"/dashboard",key:"home",icon:Home},{to:"/money",key:"money",icon:WalletCards},{to:"/recommendations",key:"recommendations",icon:CircleDollarSign},{to:"/loans",key:"loans",icon:HandCoins},{to:"/wellness",key:"wellness",icon:HeartPulse},{to:"/literacy",key:"learn",icon:GraduationCap},{to:"/ai",key:"ai",icon:Bot},{to:"/consent",key:"consent",icon:ShieldCheck},{to:"/profile",key:"profile",icon:UserRound}] as const;
function Navigation({mobile=false}:{mobile?:boolean}){const {t}=useTranslation();const path=useRouterState({select:s=>s.location.pathname});if(mobile){return <nav className="fixed inset-x-0 bottom-0 z-40 grid grid-cols-5 border-t bg-card/95 px-2 pb-[max(.5rem,env(safe-area-inset-bottom))] pt-2 backdrop-blur md:hidden">{items.slice(0,4).map(({to,key,icon:Icon})=><Link key={to} to={to} className={cn("flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl text-[10px] font-semibold text-muted-foreground",path===to&&"bg-primary-soft text-primary")}><Icon className="size-5"/><span>{t(`nav.${key}`)}</span></Link>)}<Sheet><SheetTrigger asChild><Button variant="ghost" className="h-14 flex-col gap-1 px-0 text-[10px] text-muted-foreground"><Menu className="size-5"/>{t("nav.more")}</Button></SheetTrigger><SheetContent side="bottom" className="rounded-t-3xl p-5"><SheetHeader><SheetTitle><Brand/></SheetTitle></SheetHeader><div className="mt-5 grid grid-cols-2 gap-2">{items.slice(4).map(({to,key,icon:Icon})=><Link key={to} to={to} className="flex min-h-14 items-center gap-3 rounded-xl bg-muted px-4 font-semibold"><Icon/>{t(`nav.${key}`)}</Link>)}</div></SheetContent></Sheet></nav>}return <nav className="mt-8 space-y-1">{items.map(({to,key,icon:Icon})=><Link key={to} to={to} className={cn("relative flex min-h-12 items-center gap-3 rounded-xl px-3 text-sm font-semibold text-muted-foreground transition-colors hover:bg-accent hover:text-accent-foreground",path===to&&"bg-primary-soft text-primary")}><Icon className="size-5"/><span>{t(`nav.${key}`)}</span>{path===to&&<span className="absolute -left-4 h-7 w-1 rounded-r-full bg-saffron"/>}</Link>)}</nav>}
function DemoSwitcher(){const {t}=useTranslation();const customer=useCustomer();const set=useBankBuddy(s=>s.setCustomer);return <DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" className="h-auto w-full justify-between px-3 py-3"><span className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-primary text-xs font-bold text-primary-foreground">{customer.initials}</span><span className="text-left"><span className="block text-xs">{customer.firstName}</span><span className="block text-[10px] font-normal text-muted-foreground">{t("dashboard.demo")}</span></span></span><ChevronDown className="size-3"/></Button></DropdownMenuTrigger><DropdownMenuContent align="start" className="w-64"><DropdownMenuLabel>Switch customer scenario</DropdownMenuLabel><DropdownMenuSeparator/>{demoCustomers.map((c,i)=><DropdownMenuItem key={c.id} onClick={()=>set(i)} className="min-h-12"><span className="mr-3 grid size-8 place-items-center rounded-lg bg-muted text-xs font-bold">{c.initials}</span><span><span className="block font-semibold">{c.name}</span><span className="text-xs text-muted-foreground">{c.segmentLabel} · Stress {c.stress}</span></span></DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>}
export function AppShell({children}:{children:React.ReactNode}){const customer=useCustomer();return <div className="min-h-screen bg-background"><aside className="fixed inset-y-0 left-0 z-30 hidden w-64 flex-col border-r bg-card p-4 md:flex"><Brand/><Navigation/><div className="mt-auto space-y-3"><DemoSwitcher/><p className="px-2 text-[10px] leading-relaxed text-muted-foreground">Demo controls are visible for judging and testing only.</p></div></aside><div className="md:pl-64"><header className="sticky top-0 z-20 flex h-20 items-center justify-between border-b bg-background/90 px-4 backdrop-blur md:px-8"><div className="md:hidden"><Brand compact/></div><div className="hidden items-center gap-2 text-sm font-semibold md:flex"><LayoutGrid className="size-4 text-saffron"/>Personalized for {customer.segmentLabel}</div><div className="flex items-center gap-2"><LanguageSwitcher/><Button variant="outline" size="icon" aria-label="Notifications" className="relative"><Bell/><span className="absolute right-2 top-2 size-2 rounded-full bg-saffron"/></Button></div></header><main className="mx-auto min-h-[calc(100vh-5rem)] max-w-[1500px] p-4 pb-28 md:p-8 md:pb-10">{children}</main></div><Navigation mobile/></div>}
