import { motion } from "motion/react";
import { useTranslation } from "react-i18next";
import { Check, ChevronDown, Globe2 } from "lucide-react";
import { languages } from "@/data/bankbuddy";
import { useBankBuddy } from "@/stores/bankbuddy";
import { DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
export function LanguageSwitcher({wide=false}:{wide?:boolean}){const {i18n}=useTranslation();const setLanguage=useBankBuddy(s=>s.setLanguage);const current=languages.find(x=>x.code===i18n.language)??languages[1];return <DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" className={cn("gap-2",wide&&"w-full justify-between")} aria-label="Choose language"><span className="flex items-center gap-2"><Globe2/>{current?.native}</span><ChevronDown className="size-3"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="max-h-80 w-56 overflow-y-auto">{languages.map(l=><DropdownMenuItem key={l.code} onClick={()=>setLanguage(l.code)} className="min-h-11 justify-between"><span>{l.native} <span className="text-xs text-muted-foreground">· {l.english}</span></span>{l.code===i18n.language&&<Check className="text-primary"/>}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>}
export function PageIntro({eyebrow,title,description,action}:{eyebrow?:string;title:string;description:string;action?:React.ReactNode}){return <motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} className="mb-6 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div>{eyebrow&&<div className="mb-2 text-xs font-bold uppercase text-saffron">{eyebrow}</div>}<h1 className="text-3xl font-extrabold text-foreground md:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-base text-muted-foreground">{description}</p></div>{action}</motion.div>}
export function ScoreRing({score,label,tone="primary",size="lg"}:{score:number;label:string;tone?:"primary"|"warning"|"success";size?:"sm"|"lg"}){const r=52,c=2*Math.PI*r;const color=tone==="warning"?"var(--warning)":tone==="success"?"var(--success)":"var(--primary)";return <div className={cn("relative grid shrink-0 place-items-center",size==="lg"?"size-40":"size-28")}><svg viewBox="0 0 120 120" className="absolute inset-0 size-full -rotate-90" aria-hidden="true"><circle cx="60" cy="60" r={r} fill="none" stroke="var(--muted)" strokeWidth="8"/><motion.circle cx="60" cy="60" r={r} fill="none" stroke={color} strokeWidth="8" strokeLinecap="round" strokeDasharray={c} initial={{strokeDashoffset:c}} animate={{strokeDashoffset:c*(1-score/100)}} transition={{duration:1.1,ease:"easeOut"}}/></svg><div className="text-center"><motion.div initial={{opacity:0}} animate={{opacity:1}} className={cn("font-extrabold",size==="lg"?"text-4xl":"text-2xl")}>{score}</motion.div><div className="max-w-24 text-[11px] font-semibold text-muted-foreground">{label}</div></div></div>}
